# Generated by Django 5.1 on 2024-08-29 09:18

import django.db.models.deletion
import marvel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('available', models.CharField(choices=[('English-Hindi', 'English-Hindi'), ('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to=marvel.models.movie_image_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
