# Generated by Django 5.1 on 2024-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'movies', 'verbose_name_plural': 'movies'},
        ),
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series'), ('Animation', 'Animation')], default='Movie', max_length=10),
        ),
    ]
